// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// csFs
Rcpp::List csFs(std::vector<double> uIn, std::vector<double> vIn, std::vector<double> wIn, const double& ZIn, const double& ustarIn, const double& LinvIn, const double& ZoIn, const double& bwIn, const double& sUustarIn, const double& sVustarIn, const double& kvIn, const double& C0In, const double& alphaIn, const double& MaxFetchIn);
RcppExport SEXP bLSmodelR_csFs(SEXP uInSEXP, SEXP vInSEXP, SEXP wInSEXP, SEXP ZInSEXP, SEXP ustarInSEXP, SEXP LinvInSEXP, SEXP ZoInSEXP, SEXP bwInSEXP, SEXP sUustarInSEXP, SEXP sVustarInSEXP, SEXP kvInSEXP, SEXP C0InSEXP, SEXP alphaInSEXP, SEXP MaxFetchInSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<double> >::type uIn(uInSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type vIn(vInSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type wIn(wInSEXP);
    Rcpp::traits::input_parameter< const double& >::type ZIn(ZInSEXP);
    Rcpp::traits::input_parameter< const double& >::type ustarIn(ustarInSEXP);
    Rcpp::traits::input_parameter< const double& >::type LinvIn(LinvInSEXP);
    Rcpp::traits::input_parameter< const double& >::type ZoIn(ZoInSEXP);
    Rcpp::traits::input_parameter< const double& >::type bwIn(bwInSEXP);
    Rcpp::traits::input_parameter< const double& >::type sUustarIn(sUustarInSEXP);
    Rcpp::traits::input_parameter< const double& >::type sVustarIn(sVustarInSEXP);
    Rcpp::traits::input_parameter< const double& >::type kvIn(kvInSEXP);
    Rcpp::traits::input_parameter< const double& >::type C0In(C0InSEXP);
    Rcpp::traits::input_parameter< const double& >::type alphaIn(alphaInSEXP);
    Rcpp::traits::input_parameter< const double& >::type MaxFetchIn(MaxFetchInSEXP);
    __result = Rcpp::wrap(csFs(uIn, vIn, wIn, ZIn, ustarIn, LinvIn, ZoIn, bwIn, sUustarIn, sVustarIn, kvIn, C0In, alphaIn, MaxFetchIn));
    return __result;
END_RCPP
}
// csFi
Rcpp::List csFi(std::vector<double> uIn, std::vector<double> vIn, std::vector<double> wIn, const double& ZIn, const double& ustarIn, const double& LinvIn, const double& ZoIn, const double& bwIn, const double& sUustarIn, const double& sVustarIn, const double& kvIn, const double& C0In, const double& alphaIn, const double& MaxFetchIn);
RcppExport SEXP bLSmodelR_csFi(SEXP uInSEXP, SEXP vInSEXP, SEXP wInSEXP, SEXP ZInSEXP, SEXP ustarInSEXP, SEXP LinvInSEXP, SEXP ZoInSEXP, SEXP bwInSEXP, SEXP sUustarInSEXP, SEXP sVustarInSEXP, SEXP kvInSEXP, SEXP C0InSEXP, SEXP alphaInSEXP, SEXP MaxFetchInSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<double> >::type uIn(uInSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type vIn(vInSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type wIn(wInSEXP);
    Rcpp::traits::input_parameter< const double& >::type ZIn(ZInSEXP);
    Rcpp::traits::input_parameter< const double& >::type ustarIn(ustarInSEXP);
    Rcpp::traits::input_parameter< const double& >::type LinvIn(LinvInSEXP);
    Rcpp::traits::input_parameter< const double& >::type ZoIn(ZoInSEXP);
    Rcpp::traits::input_parameter< const double& >::type bwIn(bwInSEXP);
    Rcpp::traits::input_parameter< const double& >::type sUustarIn(sUustarInSEXP);
    Rcpp::traits::input_parameter< const double& >::type sVustarIn(sVustarInSEXP);
    Rcpp::traits::input_parameter< const double& >::type kvIn(kvInSEXP);
    Rcpp::traits::input_parameter< const double& >::type C0In(C0InSEXP);
    Rcpp::traits::input_parameter< const double& >::type alphaIn(alphaInSEXP);
    Rcpp::traits::input_parameter< const double& >::type MaxFetchIn(MaxFetchInSEXP);
    __result = Rcpp::wrap(csFi(uIn, vIn, wIn, ZIn, ustarIn, LinvIn, ZoIn, bwIn, sUustarIn, sVustarIn, kvIn, C0In, alphaIn, MaxFetchIn));
    return __result;
END_RCPP
}
// csFsRK4
Rcpp::List csFsRK4(std::vector<double> uIn, std::vector<double> vIn, std::vector<double> wIn, const double& ZIn, const double& ustarIn, const double& LinvIn, const double& ZoIn, const double& bwIn, const double& sUustarIn, const double& sVustarIn, const double& kvIn, const double& C0In, const double& alphaIn, const double& MaxFetchIn);
RcppExport SEXP bLSmodelR_csFsRK4(SEXP uInSEXP, SEXP vInSEXP, SEXP wInSEXP, SEXP ZInSEXP, SEXP ustarInSEXP, SEXP LinvInSEXP, SEXP ZoInSEXP, SEXP bwInSEXP, SEXP sUustarInSEXP, SEXP sVustarInSEXP, SEXP kvInSEXP, SEXP C0InSEXP, SEXP alphaInSEXP, SEXP MaxFetchInSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<double> >::type uIn(uInSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type vIn(vInSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type wIn(wInSEXP);
    Rcpp::traits::input_parameter< const double& >::type ZIn(ZInSEXP);
    Rcpp::traits::input_parameter< const double& >::type ustarIn(ustarInSEXP);
    Rcpp::traits::input_parameter< const double& >::type LinvIn(LinvInSEXP);
    Rcpp::traits::input_parameter< const double& >::type ZoIn(ZoInSEXP);
    Rcpp::traits::input_parameter< const double& >::type bwIn(bwInSEXP);
    Rcpp::traits::input_parameter< const double& >::type sUustarIn(sUustarInSEXP);
    Rcpp::traits::input_parameter< const double& >::type sVustarIn(sVustarInSEXP);
    Rcpp::traits::input_parameter< const double& >::type kvIn(kvInSEXP);
    Rcpp::traits::input_parameter< const double& >::type C0In(C0InSEXP);
    Rcpp::traits::input_parameter< const double& >::type alphaIn(alphaInSEXP);
    Rcpp::traits::input_parameter< const double& >::type MaxFetchIn(MaxFetchInSEXP);
    __result = Rcpp::wrap(csFsRK4(uIn, vIn, wIn, ZIn, ustarIn, LinvIn, ZoIn, bwIn, sUustarIn, sVustarIn, kvIn, C0In, alphaIn, MaxFetchIn));
    return __result;
END_RCPP
}
// csFiRK4
Rcpp::List csFiRK4(std::vector<double> uIn, std::vector<double> vIn, std::vector<double> wIn, const double& ZIn, const double& ustarIn, const double& LinvIn, const double& ZoIn, const double& bwIn, const double& sUustarIn, const double& sVustarIn, const double& kvIn, const double& C0In, const double& alphaIn, const double& MaxFetchIn);
RcppExport SEXP bLSmodelR_csFiRK4(SEXP uInSEXP, SEXP vInSEXP, SEXP wInSEXP, SEXP ZInSEXP, SEXP ustarInSEXP, SEXP LinvInSEXP, SEXP ZoInSEXP, SEXP bwInSEXP, SEXP sUustarInSEXP, SEXP sVustarInSEXP, SEXP kvInSEXP, SEXP C0InSEXP, SEXP alphaInSEXP, SEXP MaxFetchInSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<double> >::type uIn(uInSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type vIn(vInSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type wIn(wInSEXP);
    Rcpp::traits::input_parameter< const double& >::type ZIn(ZInSEXP);
    Rcpp::traits::input_parameter< const double& >::type ustarIn(ustarInSEXP);
    Rcpp::traits::input_parameter< const double& >::type LinvIn(LinvInSEXP);
    Rcpp::traits::input_parameter< const double& >::type ZoIn(ZoInSEXP);
    Rcpp::traits::input_parameter< const double& >::type bwIn(bwInSEXP);
    Rcpp::traits::input_parameter< const double& >::type sUustarIn(sUustarInSEXP);
    Rcpp::traits::input_parameter< const double& >::type sVustarIn(sVustarInSEXP);
    Rcpp::traits::input_parameter< const double& >::type kvIn(kvInSEXP);
    Rcpp::traits::input_parameter< const double& >::type C0In(C0InSEXP);
    Rcpp::traits::input_parameter< const double& >::type alphaIn(alphaInSEXP);
    Rcpp::traits::input_parameter< const double& >::type MaxFetchIn(MaxFetchInSEXP);
    __result = Rcpp::wrap(csFiRK4(uIn, vIn, wIn, ZIn, ustarIn, LinvIn, ZoIn, bwIn, sUustarIn, sVustarIn, kvIn, C0In, alphaIn, MaxFetchIn));
    return __result;
END_RCPP
}
