# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

csFs <- function(uIn, vIn, wIn, ZIn, ustarIn, LinvIn, ZoIn, bwIn, sUustarIn, sVustarIn, kvIn, C0In, alphaIn, MaxFetchIn) {
    .Call('_bLSmodelR_csFs', PACKAGE = 'bLSmodelR', uIn, vIn, wIn, ZIn, ustarIn, LinvIn, ZoIn, bwIn, sUustarIn, sVustarIn, kvIn, C0In, alphaIn, MaxFetchIn)
}

csFi <- function(uIn, vIn, wIn, ZIn, ustarIn, LinvIn, ZoIn, bwIn, sUustarIn, sVustarIn, kvIn, C0In, alphaIn, MaxFetchIn) {
    .Call('_bLSmodelR_csFi', PACKAGE = 'bLSmodelR', uIn, vIn, wIn, ZIn, ustarIn, LinvIn, ZoIn, bwIn, sUustarIn, sVustarIn, kvIn, C0In, alphaIn, MaxFetchIn)
}

